### ISSUE TITLE
ParseException: expected 'end of block', found ') c'

### ISSUE THREAD

**Issue by aureole82** [r3c/cottle#12]
These lines break

    var settings = new CustomSetting
    {
        BlockBegin = "((",
        BlockEnd = "))"
    };
    var document = new SimpleDocument("a ((echo b)) c", settings);

Exception:
>Cottle.Exceptions.ParseException occurred
>  HResult=0x80131500
>  Message=expected 'end of block', found ') c'
>  Source=Cottle
>  StackTrace:
>   at Cottle.Parsers.DefaultParser.ParseCommand()
>   at Cottle.Parsers.DefaultParser.Parse(TextReader reader)
>   at Cottle.Parsers.PostParser.Parse(TextReader reader)
>   at Cottle.Documents.SimpleDocument..ctor(TextReader reader, ISetting setting)
>  ...

Tested on 1.3.2.6 and 1.4.0.1

**Comment by r3c** [comment]
Yes, character `]` can't be used as delimiters as it already have a reserved meaning when used in expressions. Please read more in [documentation](http://r3c.github.io/cottle/#delimiters_customization) about this:

> For example, choosing the ] character as a delimiter is a bad idea, as it will conflict with internal end-of-map delimiter.

**Comment by r3c** [comment]
I see you updated your issue description and tried with delimiters `((` and `))` but same problem will appear, as character `)` can also be found in math expressions. I suggest using non-ambiguous tags like `{{` and `}}` to solve your problem.

**Comment by aureole82** [comment]
Sorry, `{` and `}` characters are no option for me! And nothing else works! Even the sample in the documentation (`[[` and `]]`) doesn't run:

        [Test]
        [TestCase("(", ")")]     // ParseException : expected 'end of block', found ' c'
        [TestCase("((", "))")]   // ParseException : expected 'end of block', found ') c'
        [TestCase("<", ">")]     // ParseException : expected 'end of block', found '<EOF>'
        [TestCase("<<", ">>")]   // ParseException : expected 'expression', found ''
        [TestCase("[", "]")]     // ParseException : expected 'end of block', found ' c'
        [TestCase("[[", "]]")]   // ParseException : expected 'end of block', found '] c'
        [TestCase("{", "}")]     // Success
        [TestCase("{{", "}}")]   // Success
        [TestCase("/", "\\")]    // ParseException : expected 'end of block', found ' c'
        [TestCase("//", "\\\\")] // ParseException : expected 'end of block', found '\ c'
        public void CreateDocument(string blockBegin, string blockEnd)
        {
            var settings = new CustomSetting
            {
                BlockBegin = blockBegin,
                BlockEnd = blockEnd
            };
            var document = new SimpleDocument($"a {blockBegin}echo b{blockEnd} c", settings);
            Assert.NotNull(document);
        }

**Comment by r3c** [comment]
You're right, documentation is not up-to-date, actually no character used in an expression can be used as special delimiter. You could use `\` if you remap escape character to something else (e.g. `setting.Escape = '\0'`) but things like `(`, `>` or `[` collide with math expressions. Ambiguity can be solved by starting your sequence with a safe character like `$`, `^`, `~` or anything else that isn't a valid expression character, for example `a ($ test $) b` if your delimiters are `($` and `$)`.

Hope that helps ; I'll update documentation to make this more clear.

**Comment by aureole82** [comment]
Ok, thanks. Updating the documentation would be nice.
(Furthermore I'll take `($` and `$)` as a solution. )

**Comment by r3c** [comment]
Good! I just fixed documentation, thanks for your feedback.
