### ISSUE TITLE
Support multiple commands in a block

### ISSUE THREAD

**Issue by mthalman** [r3c/cottle#135]
I'd like to be able to use multiple commands in a single block. This would help the template file stay cleaner without all the block opening and closing characters.

As an example, this is what I have to do today:

```
{ _Declare variables }
{ set var1 to A }
{ if condition:{set var2 to B}}
```

What I'd like to be able to do is this:

```
{
  _ Declare variables
  set var1 to A
  if condition:{set var2 to B}
}
```

**Comment by r3c** [comment]
Hello @mthalman. This is a very good suggestion, I actually wanted to work on this one for quite some time. My only concern is about the possible ambiguities it would generate. For example template `{1 + 1}` prints the result of expression `1 + 1` (thanks to implicit "echo"), but with multiple commands support it could also be parsed as `{1}{ + 1}`.

This could be solved by either disabling implicit "echo" when there are more than one command in a block, or introduce some command separator (e.g. ";"). I'd rather go for the first option, but need to do a quick check to search for other points to be covered.

Maybe you already thought about this and have ideas to share?

**Comment by mthalman** [comment]
Is there a way that the continue delimiter could be used here? That might get things closer to a solution.

```
{
  _ Declare variables |
  set var1 to A |
  if condition:{set var2 to B}
}
```

**Comment by r3c** [comment]
That could be an idea 🙂 Continue delimiter currently exists only in plain text context, but that shouldn't be an issue. Please allow me some time to think this through and I'll get back to you with a proposal 🙂

**Comment by r3c** [comment]
Hi again @mthalman, your idea was actually quite brilliant, thanks a lot for the suggestion! I started to work on a patch to get this working. I'm still not done with tests and documentation yet, but I would appreciate if you could give it a try and tell me if it matches your needs. Here is a beta NuGet with commit 637a09c that adds support for composite commands: [Cottle.2.0.6-beta1.nupkg.zip](https://github.com/r3c/cottle/files/7833344/Cottle.2.0.6-beta1.nupkg.zip) (apologies for the zipped NuGet but GitHub has restrictions on file extensions).

The syntax is exactly the one you suggested:

```
{echo x|echo y}
{_ comment | echo x}
{set x to 1 | set y to 2 | if x || y:OK| dump x | dump y}
```

Note there is one gotcha:

```
{while x > 0:{x}|set x to x - 1}
```

This would cause an infinite loop, as the "set" command is not part of "while" body. It needs to be rewritten as this to work properly:

```
{while x > 0:{x|set x to x - 1}}
```

I think that's acceptable as long as it's clarified in the documentation, but I'd like to get your opinion about that 🙂

Regards.

**Comment by mthalman** [comment]
Great, thanks! I've confirmed that these changes work as I expected.



> Note there is one gotcha:
> 
> ```
> {while x > 0:{x}|set x to x - 1}
> ```
> 
> This would cause an infinite loop, as the "set" command is not part of "while" body. It needs to be rewritten as this to work properly:
> 
> ```
> {while x > 0:{x|set x to x - 1}}
> ```
> 
> I think that's acceptable as long as it's clarified in the documentation, but I'd like to get your opinion about that

I think that's reasonable and intuitive from my perspective.

I hadn't even realized that this enables new scenarios. My original intention with this request was simply to avoid verbosity in the template. But I see now that it can enable multiple commands inside of the loop and conditional blocks. That's pretty powerful.

**Comment by r3c** [comment]
Just published v2.0.6 with this change. Feel free to reopen if I missed something!

**Comment by mthalman** [comment]
@r3c - It doesn't look like these changes made it into the published NuGet. It gave me syntax errors when trying to use the continue delimiter in this way.

I downloaded https://www.nuget.org/api/v2/package/Cottle/2.0.6 and cracked it open in a disassembler to see if it contained your changes from #140. It doesn't look like they're there. I don't see a `Cottle.Parsers.ForwardParser.TryParseCommand` method, for example.

**Comment by r3c** [comment]
I recently switched to automatic NuGet publishing, and I guess this went wrong. Let me trace back what exactly happened and I'll publish an update manually if needed.

**Comment by r3c** [comment]
OK you're right, the version registered to Nuget.org as 2.0.6 doesn't match the GitHub release. I just pushed tag 2.0.7 to fix that (no change, only ref update in documentation) and manually verified the nupkg file available on Nuget.org which seems OK this time. Sorry for the noise and thank you for pointing that!
