### ISSUE TITLE
A template block at the end of a line without a carriage return will remove the new line character

### ISSUE THREAD

**Issue by solidDoWant** [r3c/cottle#153]
When reading and rendering a document with a line feed instead of a carriage return and line feed ('\n' instead of "\r\n"), if a template block is at the end of a line then the rendered document will be missing the new line character.

Example:
`test.txt` (if running this example make sure this document is using only new line chars '\n' for the end of line separator, not "\r\n")
```
First line
Second line with var 'y' with another character after the template block: {y}.
Third line with var 'x': {x}
Fourth line
```

Program.cs:
```
using Cottle;

public class Program
{
    public static void Main(string[] args)
    {
        var pathToTestFile = "test.txt";
        var pathToOutputFile = "test-output.txt";

        var testContext = Context.CreateBuiltin(
            new Dictionary<Value, Value>
            {
                ["x"] = "x",
                ["y"] = "y",
            }
        );

        using var testReader = new StreamReader(pathToTestFile);
        var readDoc = Document.CreateDefault(testReader);
        var output = readDoc.Document.Render(testContext);

        using var outputFileWriter = new StreamWriter(pathToOutputFile);
        outputFileWriter.Write(output);
    }
}
```

The written file will read as follows:
```
First line
Second line with var 'y' with another character after the template block: {y}.
Third line with var 'x': {x}Fourth line
```

As you can see above the third and fourth lines are concatenated.

**Comment by r3c** [comment]
Hello @solidDoWant, this is the behavior triggered by `TrimFirstAndLastBlankLines` trimming strategy, which is the one used by default (you can read more about it [here](https://cottle.readthedocs.io/en/stable/page/04-configuration.html#trimfirstandlastblanklines)). If it doesn't match what you'd expect, maybe you could either add an extra blank line between third and fouth one so that one \n is preserved, or switch to `TrimNothing` strategy to disable this behavior entirely?

**Comment by solidDoWant** [comment]
> this is the behavior triggered by `TrimFirstAndLastBlankLines` trimming strategy
Thank you! That's exactly what I was looking for. I must have missed it while reading through the docs. Thanks for your help and the fast response!
