### ISSUE TITLE
Consider supporting Native Documents when compiled as NativeAOT

### ISSUE THREAD

**Issue by mikeball** [r3c/cottle#165]
Please consider supporting NativeAOT for Cottle Native Documents (https://cottle.readthedocs.io/en/stable/page/04-configuration.html#native-documents). With .NET 7 soon to arrive, it will support compilation to native self contained binaries(https://github.com/dotnet/runtime/issues/61231) will likely be a common scenario. My specific use case is planning for a NativeAOT friendly web framework that is presently only in planning stage so not actual production use of Cottle yet.

Using the latest .Net 7 preview 5 I was able to get a normal Cottle document declared as a string variable to compile with NativeAOT, and run successfully.
```csharp
var template = "Hello {who}, stay awhile and listen!";
var documentResult = Document.CreateDefault(template); // Create from template string
var document = documentResult.DocumentOrThrow; // Throws ParseException on error
var context = Context.CreateBuiltin(new Dictionary<Value, Value>
{
    ["who"] = "my friend" // Declare new variable "who" with value "my friend"
});
Console.Write(document.Render(context));
```
This package reference must be included to build the NativeAOT 
```xml
<PackageReference Include="Microsoft.DotNet.ILCompiler" Version="7.0.0-preview.5.22301.12" />

```
now publish as a NativeAOT exe
```
C:\example-template> dotnet publish -c Release -r win-x64 --output ./out
...
C:\Users\mike\.nuget\packages\cottle\2.0.8\lib\net6.0\Cottle.dll : warning IL2104: Assembly 'Cottle' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries [C:\Users\mike\work\src\example-template\example-template.csproj]
C:\Users\mike\.nuget\packages\cottle\2.0.8\lib\net6.0\Cottle.dll : warning IL3053: Assembly 'Cottle' produced AOT analysis warnings. [C:\Users\mike\work\src\example-templa
te\example-template.csproj]
C:\Users\mike\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilcompiler\7.0.0-preview.5.22301.12\framework\System.Linq.Expressions.dll : warning IL3053: Assembly 'System.Linq.Expressions' produ
ced AOT analysis warnings. [C:\Users\mike\work\src\example-template\example-template.csproj]

```
A couple compiler warning, but it runs as native exe, awesome!
```
C:\example-template> .\out\example-template.exe
Hello my friend, stay awhile and listen!
```

However, when attempting to use Cottle Native Document with the example code
```csharp
var template = "Hello {who}, stay awhile and listen!";
var document = Document.CreateNative(template).DocumentOrThrow;
var context = Context.CreateBuiltin(new Dictionary<Value, Value>
{
    ["who"] = "my friend" // Declare new variable "who" with value "my friend"
});
Console.Write(document.Render(context));
```
The NativeAOT exe builds successfully (with same warnings as above)
```
dotnet publish -c Release -r win-x64 --output ./out
```

Unfortunately the exe with Cottle Native Document fails with this error when executed
```
PS C:\example-template> .\out\example-template.exe
Unhandled Exception: System.PlatformNotSupportedException: Dynamic code generation is not supported on this platform.
   at System.Reflection.Emit.ReflectionEmitThrower.ThrowPlatformNotSupportedException() + 0x33
   at Cottle.DynamicMethodCreator`1..ctor() + 0x106
   at Cottle.Documents.Emitted.Program.Create(IStatementGenerator, IReadOnlyList`1) + 0x2a
   at Cottle.Documents.CompiledDocument`2..ctor(IAssembler`1, Func`2, Statement) + 0x49
   at Cottle.Document.<>c.<CreateNative>b__4_0(Statement) + 0x23
   at Cottle.Document.Create(TextReader, DocumentConfiguration, Func`2) + 0xd1
   at Cottle.Document.CreateNative(TextReader, DocumentConfiguration) + 0xb7
   at Cottle.Document.CreateNative(String, DocumentConfiguration) + 0x58
   at Program.<Main>$(String[]) + 0x9c
   at example-template!<BaseAddress>+0x3213f3
```

**Comment by r3c** [comment]
Hello @mikeball! From the samples you posted it seems this is caused by NativeAOT not supporting dynamic code generator (yet), which is the solution Cottle relies on for producing native documents. If that's correct, I'm not sure there is much I can do about it other than waiting for this support to be implemented ; do you feel I'm missing something? 🙂

**Comment by mikeball** [comment]
I was thinking about the potential to use c# source generators rather than reflection. That could remove the need to have two method of generating a Cottle document, providing  highest performance in the default usage, and should be aot compatible too.

https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview

**Comment by mikeball** [comment]
No worries and thanks, just wanted to bring up the potential of doing such a project. Going to close this issue for now.
