### ISSUE TITLE
Getting fields of report, before actual rendering

### ISSUE THREAD

**Issue by veantm** [r3c/cottle#175]
Hi!

How can i get read all va­riables
referenced in my document before creating context and render a document?

For example, i had next template:

"Hello {name}!

{for tag in tags:
{tag.Name}
}"

How can i get list of: name, tags(Name)?

I always get dynamic report from frontend. And for creating context with data for it i must build dynamic sql query. But i cant do this without list of fields in report.

**Comment by veantm** [comment]
![image](https://user-images.githubusercontent.com/20851913/204357434-30206411-b509-47b0-9b62-f81c3dbc5f42.png)

For now, i see fields in non-public members, but can't access them in code.

**Comment by r3c** [comment]
Hello @veantm, I'm not sure I get your question exactly, but I think this is what is described under section ["Spying values"](https://cottle.readthedocs.io/en/stable/page/05-advanced.html#spying-values) of the documentation. You'll need to render your document at least once with a blank context (just pass `Context.Blank`) and you'll get the list of global variables used in your document.

Note you won't get any dynamic field from these values, as they would require rendering the document with some actual context (in your example the iteration over tags would be no-op), but it may be OK given your description.

**Comment by veantm** [comment]
Yes, is work's. Thank you.

> Hello @veantm, I'm not sure I get your question exactly, but I think this is what is described under section ["Spying values"](https://cottle.readthedocs.io/en/stable/page/05-advanced.html#spying-values) of the documentation. You'll need to render your document at least once with a blank context (just pass `Context.Blank`) and you'll get the list of global variables used in your document.
> 
> Note you won't get any dynamic field from these values, as they would require rendering the document with some actual context (in your example the iteration over tags would be no-op), but it may be OK given your description.
