### ISSUE TITLE
netstandard1.5 release

### ISSUE THREAD

**Issue by hjalle** [r3c/cottle#18]
Will there be a release for netstandard1.5 on nuget?

**Comment by r3c** [comment]
Yes, I'll publish a new package compatible with .NET Core as soon as I have access to a computer with suitable requirements, hopefully next week.

**Comment by hjalle** [comment]
Perfect 👍

**Comment by r3c** [comment]
Just published v1.4.0.3 with netstandard1.5 + net40 builds ; huge thanks to @gboucher90 for actually doing all the work!
