### ISSUE TITLE
Obscure exceptions when `Value.FromReflection` fails

### ISSUE THREAD

**Issue by paviad** [r3c/cottle#193]
If you provide a context member in the form of `Value.FromReflection(obj)` and the object contains properties that are incompatible, you get a very obscure exception that hides the real problem point.

I would expect the exception to pinpoint the property that is problematic.

**Comment by r3c** [comment]
Merged & released in [v2.0.10](https://github.com/r3c/cottle/releases/tag/2.0.10), thanks a lot for your contribution! 🙂
