### ISSUE TITLE
Boolean value is not being rendered when is false

### ISSUE THREAD

**Issue by omarisai** [r3c/cottle#22]
Having a variable called **b** with value **false**:

**b = {b}**

result is: **b =** 

when **b** is **true** the result is: **b = true**

**Comment by omarisai** [comment]
Thanks! Changing the topic, is there some way to evaluate a string expression from c# only with the store object?

like: **result = Cottle.Evaluate("a + b + c", store);**

**Comment by r3c** [comment]
There is no builtin `Evaluate` method but you can easily simulate one by injecting your own custom .NET method (see "Custom .NET methods" section in the documentation) that will receive result of your expression and save it to some variable. It could look like this (I didn't try to compile, you may have to adapt this code a bit):

```
public static Value Evaluate(string expression, IStore store)
{
    Value result; // Will be used to save expression result

    store["set_result"] = new NativeFunction(arguments => result = arguments[0], 1);

    var document = new SimpleDocument("set_result(" + expression + ")");
    document.Render(store);

    return result;
}
```
Hope that helps.

**Comment by omarisai** [comment]
Thank you very much, it worked!

**Comment by r3c** [comment]
You're welcome :)
