### ISSUE TITLE
'\n' seems not preserved after Render().

### ISSUE THREAD

**Issue by kilasuelika** [r3c/cottle#234]
Following code:
```
using System;
using System.Collections.Concurrent;
using Cottle;

var dict = new ConcurrentDictionary<Value, Value>
{
    ["y"] = Value.FromString("A")
};
var context = Context.CreateBuiltin(dict);
var template = "y is {y}\nxxc";
var doc = Cottle.Document.CreateDefault(template).Document;
var c = doc.Render(context);
Console.WriteLine(c);

```
Prints:
```
y is Axxc
```
The newline character '\n' disappeared. I also found if Render "y is A\nxxc", e.g. no {} block, then the \n is preserved correctly.

**Comment by r3c** [comment]
Hello,

This is indeed expected behavior from default text trimming configuration described here: https://cottle.readthedocs.io/en/latest/page/04-configuration.html#trimfirstandlastblanklines

You'll also find other options in this page, and can define your own if none match your needs.

**Comment by kilasuelika** [comment]
> Hello,
> 
> This is indeed expected behavior from default text trimming configuration described here: https://cottle.readthedocs.io/en/latest/page/04-configuration.html#trimfirstandlastblanklines
> 
> You'll also find other options in this page, and can define your own if none match your needs.

Thank you. Not I understand.
