### ISSUE TITLE
If evaluation with || and = 

### ISSUE THREAD

**Issue by tim-arheit** [r3c/cottle#28]
I believe the following syntax should be allowed:
{ if Transaction.TransactionType = "Refund" || Transaction.TransactionType = "Void"  :  -}

but it results in the error Message: expected parenthesis end (')'), found unknown operator

I've also tried formats
{ If (x = "a" || y="b") : - }
{ If (x = "a") || (y="b") : - }

The docs show (x < 1 || x > 9) as an example, so I would expect the same would work with =
I have a  workaround for our case, but this might be an issue?

This works as expected:
{ if Transaction.TransactionType = "Refund"  :  -}

**Comment by r3c** [comment]
Hello!

I'm unable to reproduce your issue with default configuration, the snippets you provided seem to be parsed and rendered correctly in the few tests I performed. Did you change Cottle delimiters in your code by any chance? Would you be able to share a full example that would reproduce this issue?

**Comment by r3c** [comment]
Hey @tim-arheit, any news about this issue? Please feel free to reopen if you have trouble getting this to work 🙂
