### ISSUE TITLE
ReflectionValue and decimal

### ISSUE THREAD

**Issue by mcdee** [r3c/cottle#7]
I have objects that I am exposing to Cottle scripts using ReflectionValue.  It all seems to work well, except that I cannot obtain decimal values.  From looking at the code it appears that ReflectionValue does not support decimal.  Is it possible to add decimal to the list of supported types?

**Comment by r3c** [comment]
Hello @mcdee , you're right decimal type and a few others were missing. I just fixed that in version 1.3.2.2, you'll find it on nuget in a few minutes :) (or you can just build from current master)
