### ISSUE TITLE
DateTime support

### ISSUE THREAD

**Issue by cjlotz** [r3c/cottle#92]
Hello, is it possible to format and display DateTime values.  I don't think this supported out-of-the-box but was thinking of converting the DateTime to number using DateTime.Ticks and using date time format specifier and the format function to display.  From my tests this doesn't seem possible?

**Comment by r3c** [comment]
Hello @cjlotz, it is supported indeed, however the documentation is probably not very clear about it 🙂

You can use the [format](https://cottle.readthedocs.io/en/stable/page/03-builtin.html#format-value-format-culture) builtin function to format any Epoch timestamp (in seconds) into a readable datetime using a custom format. The documentation shows an example, let me know if you need more information about how to achieve this 🙂
