### ISSUE TITLE
Dynamic Type support

### ISSUE THREAD

**Issue by cjlotz** [r3c/cottle#94]
The library feels like a great, lightweight template engine alternative.  I know you are able to construct a value using reflection from an object type, but was wondering whether it is possible to add support for constructing a `Value` using a dynamic type like most of the other template engines support, i.e.

```c#
var context = Context.CreateBuiltin(new Dictionary<Value, Value>
{
    ["model"] = Value.FromDynamic(new { FirstName = "Joe", LastName = "Soap"})
});
```

**Comment by r3c** [comment]
Isn't `Value.FromReflection` OK for your use case? (https://cottle.readthedocs.io/en/stable/page/05-advanced.html#réflection-values)

**Comment by cjlotz** [comment]
Just a follow up - not a major blocker in our use case.  We can probably create an extension to walk through the `DynamicObject` and create a Value (map) as the current reflection implementation does

**Comment by r3c** [comment]
Hey @cjlotz! I first thought this should have worked with `Value.FromReflection` but it doesn't. I had a quick look at how anonymous types are generated, and it seems the actual field names are generated and don't exactly match the one specified in your code (e.g. in your example "FirstName" gets compiled into something like "<FirstName>i__Field". I don't know if there is a reliable way to find back the original name, nor if this is a good idea or not ; first answers I saw on SO hint about such anonymous types being intended for private use only and never leave the scope of the method they're defined in.

You probably have more experience than me with these times ; while I'm digging a bit into this topic, would you mind sharing any solution you may have in mind already?

**Comment by cjlotz** [comment]
Yes, dynamic types, but my example is using an anonymous type, so sorry for the confusion.  As mentioned, our use case is quite specific and we can create an extension to walk our `DynamicRecord` container (that inherits from `DynamicObject`) to populate its values into a Value map.  So don't worry too much about this.
