### ISSUE TITLE
Html escaping

### ISSUE THREAD

**Issue by cjlotz** [r3c/cottle#95]
Hello, following on the [example from the docs](https://cottle.readthedocs.io/en/stable/page/02-language.html#text-escaping-wrap-unwrap) on how to escape templates using the `wrap` function, I created the following HTML e-mail template:

```c#
var template = @"
{# wrap html:
Welcome to {# SystemName #}, {# Entity['User->FullName'] #}!<br><br>To activate your account, please click the <a href='{# SystemUrl #}'>following link</a>.<br><br>Regards
#}";
    
var configuration = new DocumentConfiguration
{
    BlockBegin = "{#",
    BlockEnd = "#}"
};

var htmlEncode = Function.CreatePure1((s, v) => HttpUtility.HtmlEncode(v));
var context = Context.CreateBuiltin(new Dictionary<Value, Value>()
{
    ["html"] = Value.FromFunction(htmlEncode),
    ["SystemName"] = "My System Name",
    ["SystemUrl"] = @"https://myurl.com/",
    ["Entity"] = new Dictionary<Value, Value>
        {
            ["User->FullName"] = "Joe Soap"
        }
});

var document = Document.CreateDefault(template, configuration).DocumentOrThrow;
```

When the template gets rendered, it produces the following output

```html
Welcome to &quot;My System Name&quot;, &quot;Joe Soap&quot;!<br><br>To activate your account, please click the <a href='&quot;https://myurl.com/&quot;'>following link</a>.<br><br>Regards
```

Notice that the SystemName and Entity string variables are escaped using `&quot;`.  Is that the expected behaviour? Shouldn't string variable be printed as is unless I provide an actual `\"` escape character in the variable like your documentation example shows?

**Comment by r3c** [comment]
Hello @cjlotz, sorry there is indeed a typo in the doc ; the `htmlEncode` function should declared like this:
```csharp
var htmlEncode = Function.CreatePure1((s, v) => HttpUtility.HtmlEncode(v.AsString));
```
Mind the ".AsString" property after "v", otherwise the wrong overload of `HttpUtility.HtmlEncode` is invoked (the one that accepts an `object` type) and results in unwanted quotes to be added. I'll fix the doc ASAP, thanks for reporting this!

**Comment by cjlotz** [comment]
Makes sense.  Thx

**Comment by r3c** [comment]
Doc is fixed. Feel free to reopen ticket if you still experience an issue with this code sample.
